# Generated by Django 3.0.4 on 2020-03-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20200330_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='userdetails',
        ),
    ]
