# Generated by Django 3.0.4 on 2020-03-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_usersdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
