# Generated by Django 3.0.4 on 2020-05-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_assign_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Description',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
    ]
