# Generated by Django 3.0.4 on 2020-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_ask_doubts'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
            ],
        ),
    ]
