# Generated by Django 3.0.4 on 2020-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_add_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materials',
            field=models.FileField(upload_to=''),
        ),
    ]
