# Generated by Django 3.0.4 on 2020-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_auto_20200508_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='course_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
